jobs:
  test:
    executor: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          command: |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py
            pip install ansible
            wget --quiet https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
            sudo unzip terraform_0.12.20_linux_amd64.zip -d /usr/local/bin
            wget --quiet https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
            sudo unzip packer_1.5.5_linux_amd64.zip -d /usr/local/bin
          name: Install Terraform
      - run:
          command: go test ~/project/test -v -timeout 45m
          no_output_timeout: 45m
          name: "go test"
      - run:
          name: Destroy on failure
          command: |
            wget https://github.com/gruntwork-io/cloud-nuke/releases/download/v0.1.13/cloud-nuke_linux_amd64 -O ./cloud-nuke
            chmod +x ./cloud-nuke
            ./cloud-nuke aws --force
          when: on_fail
orbs:
  go: circleci/go@0.2.0
  node: circleci/node@1.1.6
version: 2.1
workflows:
  version: 2
  default:
    jobs:
      - test:
          context: azure-ci-1
